application: demeetr
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /logo
  static_dir: logo

- url: /js
  static_dir: js

- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: demeetr.app

- url: /signup
  script: demeetr.app
  secure: always

- url: /login
  script: demeetr.app
  secure: always

- url: /fblogin
  script: demeetr.app
  secure: always

- url: /fbauth
  script: demeetr.app
  secure: always

# - url: /googlelogin
#   script: demeetr.app
#   secure: always

# - url: /googleauth
#   script: demeetr.app
#   secure: always

- url: /.*
  script: demeetr.app
  # login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

- name: pycrypto
  version: "latest"